config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#show', page: "index"

  resources :officers, path: "officers", only: [:index, :new, :create, :edit, :update]
  resources :events, path: "events", except: [:show]
  resources :admin, only: [:index]

  Rails.application.routes.draw do
   get "pages/:page" => "pages#show"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  # validations
  validates :headline, presence: true
  validates :date_time, presence: true
  validates :room, presence: true
  validates :building, presence: true
  validates :address, presence: true

  def self.upcoming
    where(["date_time >= ?", DateTime.current]).order("date_time ASC")
  end

  def self.past
    where(["date_time < ?", DateTime.current]).order("date_time DESC")
  end
end

app/models/event_presenter.rb
class EventPresenter
  attr_reader :event
  delegate :headline, :abstract, :company, :id, :speaker, to: :event

  def initialize(event)
    @event = event
  end

  def image
    nil
  end

  def location
    Location.new(
      room: @event.room,
      building: @event.building,
      address: @event.address,
    )
  end

  def full_time
    @event.date_time.to_formatted_s(:long_ordinal)
  end
end

app/models/location.rb
class Location
  include ActiveModel::Model
  attr_accessor :room, :building, :address

  def short_form
    "#{room} #{building}"
  end

  def long_form
    "#{room} #{building}, #{address}"
  end

  def self.default
    new(
      room: 108,
      building: "West Village G",
      address: "450 Parker Street",
    )
  end
end

app/models/officer.rb
class Officer < ApplicationRecord

  # Validations
  validates :name, presence: true
  validates :position, presence: true
  validates :image_path, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin, :super_admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_as_admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_as_admin
    authenticate_user! && admin_user?
  end

  def authenticate_as_super_admin
    authenticate_user! && super_admin_user?
  end

  def admin_user?
    current_user && (current_user.admin? || current_user.super_admin?)
  end

  def super_admin_user?
    current_user && current_user.super_admin?
  end

  def default_meeting_details
    OpenStruct.new(
      location: default_location,
      time: "6:00 PM",
      composite_meeting_time: "#{default_location.short_form} at 6:00 PM",
      composite_meeting_schedule: "Wednesday at 6:00 PM",
    )
  end

  helper_method :admin_user?, :super_admin_user?, :default_meeting_details

  private

  def default_location
    Location.default
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_as_admin, except: [:index]

	def index
		@upcoming_events = Event.upcoming.map{ |event| EventPresenter.new(event) }
    @past_events = Event.past.map{ |event| EventPresenter.new(event) }
	end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event && @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.delete
      redirect_to events_path
    else
      render :edit
    end
  end

	private

	def event_params
		params.require(:event).permit(
      :headline,
      :abstract,
      :room,
      :building,
      :address,
      :date_time,
      :speaker,
      :company,
      :company_logo
    )
	end
end

app/controllers/officers_controller.rb
class OfficersController < ApplicationController
  before_action :authenticate_as_admin, only: [:new, :create]
  before_action :authenticate_as_super_admin, only: [:edit, :update]

  def index
    @officers = Officer.all
  end

  def new
  	@officer = Officer.new
  end

	def create
		@officer = Officer.new(officer_params)
		if @officer.save
      redirect_to officers_path
		else
      render :new
    end
	end

  def edit
    @officer = Officer.find(params[:id])
  end

  def update
    @officer = Officer.find(params[:id])
    if @officer && @officer.update(officer_params)
      redirect_to officers_path
    else
      render :edit
    end
  end

	private

	def officer_params
		params.require(:officer).permit(:name, :year, :position, :image_path)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	# display a view in the pages directory, also used for index
	def show
		if valid_page?
			render template: "pages/#{params[:page]}"
		else
			redirect_to root_path
		end
	end

	# check if the file exists in the pages view directory
	private

	def valid_page?
		File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/external_links_helper.rb
module ExternalLinksHelper
  def facebook_page_link
    "https://www.facebook.com/nuacm"
  end

  def mailing_list_link
    "http://eepurl.com/EkKhD"
  end

  def email_raw
    "#116;o&#58;&#37;61&#99;m&#64;cc&#115;&#46;&#110;&#37;&#54;&#53;u&#46;e&#100;u"
  end

  def email_redirect
    "mail&#116;o&#58;&#37;61&#99;m&#64;cc&#115;&#46;&#110;&#37;&#54;&#53;u&#46;e&#100;u"
  end

  def nuacm_logo_url
    "https://image.ibb.co/nfWVNG/logo.png"
  end
end

app/helpers/header_helper.rb
module HeaderHelper
  def session_account_button
    if user_signed_in?
      link_to t("nav.logout"), destroy_user_session_path, method: :delete, class: "button"
    else
      link_to t("nav.login"), new_user_session_path, class: "button"
    end
  end

  def admin_account_buttons
    if admin_user?
      content_tag :li do
        link_to t("nav.admin"), admin_index_path, class: "button"
      end
    end
  end
end

app/views/admin/index.html.erb
<div class="container">
  <div class="admin-wrapper">
    <h2 class="admin-header"><%= t("admin.header") %></h2>
    <div class="form-row">
      <div class="form-input">
        <%= link_to t("admin.buttons.new_event"), new_event_path, class: "button" %>
      </div>
      <div class="form-input">
        <%= link_to t("admin.buttons.new_officer"), new_officer_path, class: "button" %>
      </div>
    </div>
  </div>
</div>

app/views/events/_event_listing.html.erb
<div class="event-item">
  <div class="event-information">
    <h3 class="event-headline"><%= event.headline %></h3>

    <div class="event-row">
      <% if event.speaker.present? %>
        <div class="event-detail">
          <div class="visual-label"><%= t("events.labels.speaker") %></div>
          <%= event.speaker %>
        </div>
      <% end %>
      <% if event.company.present? %>
        <div class="event-detail">
          <div class="visual-label"><%= t("events.labels.company") %></div>
          <%= event.company %>
        </div>
      <% end %>
    </div>

    <div class="event-row">
      <div class="event-detail">
        <div class="visual-label"><%= t("events.labels.time") %></div>
        <%= event.full_time %>
      </div>
      <div class="event-detail">
        <div class="visual-label"><%= t("events.labels.location") %></div>
        <%= event.location.long_form %>
      </div>
    </div>

    <% if event.abstract.present? %>
      <div class="event-row">
        <div class="event-detail">
          <div class="visual-label"><%= t("events.labels.abstract") %></div>
          <%= event.abstract %>
        </div>
      </div>
    <% end %>

    <% if admin_user? %>
      <div class="event-admin-buttons">
        <%= link_to t("events.buttons.edit"), edit_event_path(event.id), class: "button" %>
      </div>
    <% end %>

  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="edit-event-wrapper">
    <%= form_for @event do |f| %>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :headline %>
          <%= f.text_field :headline %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :abstract %>
          <%= f.text_area :abstract %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :date_time %>
          <%= f.datetime_local_field :date_time %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :speaker %>
          <%= f.text_field :speaker %>
        </div>
        <div class="form-input">
          <%= f.label :company %>
          <%= f.text_field :company %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :room %>
          <%= f.text_field :room %>
        </div>
        <div class="form-input">
          <%= f.label :building %>
          <%= f.text_field :building %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :address %>
          <%= f.text_field :address %>
        </div>
      </div>
      <div class="edit-event-buttons">
      <%= f.submit class: "button" %>
        <%= link_to t("events.buttons.delete"), event_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" }, class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container-small">
  <% if @upcoming_events && !@upcoming_events.empty? %>
    <div class="event-group">
    	<div class="page-heading">
    		<h2><%= t("events.headlines.upcoming_events") %></h2>
    	</div>
    	<div class="event-listing">
    		<% @upcoming_events.each do |event| %>
    			<%= render partial: "event_listing", locals: { event: event } %>
    		<% end %>
    	</div>
    </div>
  <% end %>

  <% if @past_events && !@past_events.empty? %>
    <div class="event-group">
      <div class="page-heading">
        <h2><%= t("events.headlines.past_events") %></h2>
      </div>
      <div class="event-listing">
        <% @past_events.each do |event| %>
          <%= render partial: "event_listing", locals: { event: event } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= form_for @event, html: { class: "form-wrapper event-form" } do |f| %>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :headline %>
        <%= f.text_field :headline %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :abstract %>
        <%= f.text_area :abstract %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :date_time %>
        <%= f.datetime_local_field :date_time %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :speaker %>
        <%= f.text_field :speaker %>
      </div>
      <div class="form-input">
        <%= f.label :company %>
        <%= f.text_field :company %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :room %>
        <%= f.text_field :room, value: default_meeting_details.location.room %>
      </div>
      <div class="form-input">
        <%= f.label :building %>
        <%= f.text_field :building, value: default_meeting_details.location.building %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-input">
        <%= f.label :address %>
        <%= f.text_field :address, value: default_meeting_details.location.address %>
      </div>
    </div>
    <%= f.submit class: "button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Northeastern University ACM</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render partial: "shared/google_tag_manager" %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="main">
      <main role="main">
        <%= yield %>
      </main>
    </div>
    <%= render "shared/footer" %>
    <%= render "shared/javascripts" %>
  </body>
</html>

app/views/officers/edit.html.erb
<div class="container">
  <div class="officer-form">
    <h2><%= t("officers.headers.edit_officer") %></h2>
    <%= form_for @officer do |f| %>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :position %>
          <%= f.text_field :position %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :image_path %>
          <%= f.text_field :image_path %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-input">
          <%= f.label :year %>
          <%= f.text_field :year %>
        </div>
      </div>
      <%= f.submit class: "button" %>
    <% end %>
  </div>
</div>

app/views/officers/index.html.erb
<div class="officers">
	<div class="container">
		<% @officers.each do |officer| %>
			<div class="officer-bio">
				<% if officer.image_path.present? %>
					<div class="officer-image">
						<%= image_tag officer.image_path, alt: "Officer Photo", class: "officer-image" %>
					</div>
				<% end %>
				<div class="col-line-items">
					<div class="col-line-item">
						<div class="col-line-item-label visual-label"><%= t("officers.bio.labels.name") %></div>
						<div class="col-line-item-info"><%= officer.name %></div>
					</div>
					<div class="col-line-item">
						<div class="col-line-item-label visual-label"><%= t("officers.bio.labels.year") %></div>
						<div class="col-line-item-info"><%= officer.year %></div>
					</div>
					<div class="col-line-item">
						<div class="col-line-item-label visual-label"><%= t("officers.bio.labels.position") %></div>
						<div class="col-line-item-info"><%= officer.position %></div>
					</div>
				</div>
				<% if admin_user? %>
					<%= link_to t("officers.buttons.edit_officer"), edit_officer_path(officer), class: "button" %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/index.html.erb
<body>
		<div class="row">
			<div class='col-xl-2 col-md-2 col-sm-1 col-xs-1'></div>
			<div class="col-xl-8 col-md-8 col-sm-10 col-xs-10">
				<h3><%= t("home.mission") %></h3>
				<p>
					As leaders of the Northeastern University chapter of the Association of Computing Machinery, our goal is to expose students to a diverse range of computer science topics, and build a community within the university. We believe that there's a lot more to computer science than what you see in the classroom, and we bring people together by hosting events that further their knowledge of the field.
				</p>
				<h3><%= t("home.events") %></h3>
				<p>
					We have meetings <strong><%= default_meeting_details.composite_meeting_schedule %></strong> during the academic year. We usually meet in <strong><%= default_meeting_details.location.short_form %></strong>, which is located at <%= default_meeting_details.location.address %>. Our past events include tech talks, workshops, coding competitions, and many others. Event dates and locations may change from week to week.
				</p>
				<p>
					To find out more about our upcoming events, please check our
					<%= link_to t("links.facebook"), facebook_page_link %>. We use facebook for most of our event scheduling purposes, so it is updated very regularly. You can also sign up for our <%= link_to t("links.mailing_list"), mailing_list_link %> to receive event updates by email.
				</p>
				<h3><%= t("home.contact") %></h3>
				<p>
					For general questions, comments, or event suggestions, the best way to reach us is by email at <a href='mail&#116;o&#58;&#37;61&#99;m&#64;cc&#115;&#46;&#110;&#37;&#54;&#53;u&#46;e&#100;u'>&#97;cm&#64;c&#99;s&#46;neu&#46;edu</a>. We are always looking for speakers and event partners, so please contact us if you'd like to work together!
				</p>
			</div>
		</div>
		</div>
</body>

app/views/shared/_email-signup-form.html.erb
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://neu.us7.list-manage.com/subscribe/post?u=c63e996ca44a0ec7d4dd8f944&amp;id=7e5f3fd9f8" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address </label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
  <label for="mce-FNAME">First Name </label>
  <input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
  <label for="mce-LNAME">Last Name </label>
  <input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c63e996ca44a0ec7d4dd8f944_7e5f3fd9f8" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->

app/views/shared/_footer.html.erb
<section id="footer">
	<div class="container">
    <div class="footer-content">
  		<div class="footer-info">
        <p> Interested in giving a talk, or partnering with NuACM? Drop us a line at <a href='mail&#116;o&#58;&#37;61&#99;m&#64;cc&#115;&#46;&#110;&#37;&#54;&#53;u&#46;e&#100;u'>&#97;cm&#64;c&#99;s&#46;neu&#46;edu</a></p>
        <p> We're open source on <a href="https://github.com/nuacm/Website-Master">Github</a>!</p>
  			<p>&copy; NUACM 2018</p>
  		</div>
      <div class="footer-action">
        <ul class="horizontal-list">
          <li>
            <%= link_to facebook_page_link, class: "button light social-media-button" do %>
              <%= icon("facebook-official") %>
            <% end %>
          </li>
          <li>
            <a href="mail&#116;o&#58;&#37;61&#99;m&#64;cc&#115;&#46;&#110;&#37;&#54;&#53;u&#46;e&#100;u" class="button light social-media-button">
              <%= icon("envelope") %>
            </a>
          </li>
        </ul>
      </div>
    </div>
	</div>
</section>

app/views/shared/_google_tag_manager.html.erb
<%= content_for :scripts do %>
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TP75C84&gtm_auth=HkpO0ssHhtNbCESFtP8B-g&gtm_preview=env-2&gtm_cookies_win=x"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=HkpO0ssHhtNbCESFtP8B-g&gtm_preview=env-2&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-TP75C84');</script>
  <!-- End Google Tag Manager -->
<% end %>

app/views/shared/_header.html.erb
<div class='navbar'>
  <div class="container">
    <div class='navbar-content'>
      <%= link_to (image_tag nuacm_logo_url, alt: "NUACM Logo", class: "logo", size: "250x80"), root_path %>
        <div class='navbuttons'>
          <ul class='horizontal-list'>
            <li><%= session_account_button %></li>
          </ul>
          <ul class='horizontal-list'>
            <li><%= link_to t("nav.events"), events_path, class: "button" %></li>
            <li><%= link_to t("nav.officers"), officers_path, class: "button" %></li>
            <%= admin_account_buttons %>
          </ul>
        </div>
    </div>
  </div>
</div>

app/views/shared/_javascripts.html.erb
<%= yield :scripts %>